### ISSUE TITLE
generating DB comments from __doc__ special variable

### ISSUE THREAD

**Issue by Koldar** [vanadium23/django-db-comments#6]
* Django Db Comments version: 0.2.2
* Django version: 3.1
* Python version: 3.8
* Operating System: Windows 10 Pro

### Description

This is a feature request: it would be possible to fetch the database comment not only from `help_text` and from `verbose_name` but also from the special `__doc__` element attached to the column field? For instance, it would be great to do something like:

```
name = models.CharField(name='name', max_length=255, null=False)
"""
Name of the my awesome entity
"""
```
In this way we could fetch the help not only in the database, but also from the content assist (e.g., in PyCharm IDE) as well.

What do you think?

**Comment by vanadium23** [comment]
I'll check if a django field has a `__doc__` property in it.
